version: "3.9"

services:
  db:
    container_name: mvav-db
    image: postgis/postgis:15-3.4
    ports:
      - 5432:5432
    volumes:
      - mvav_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mvav-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: psql -U postgres -c "select 1"
      interval: 2s
      retries: 10
      timeout: 1s
  backend:
    container_name: backend
    build: ./backend
    volumes:
      # Mount the root folder that contains .git
      - .:/code:cached
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=mvav-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy
  client: 
    container_name: client
    build: ./client
    command: yarn dev --port 3000 --host 0.0.0.0
    volumes:
      # this is needed so that node_modules are not erased by the host volume when starting the container 
      - /code/client/node_modules
      # Mount the root folder that contains .git
      - .:/code:cached
    ports: 
      - 3000:3000

volumes:
  mvav_data:
    external: true
