version: "3.9"

services:
  db:
    container_name: mvav-db
    image: postgis/postgis:15-3.4
    ports:
      - 5432:5432
    volumes:
      - mvav_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mvav-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: psql -U postgres -c "select 1"
      interval: 2s
      retries: 10
      timeout: 1s
  backend:
    container_name: backend
    build: ./backend
    volumes:
      - ./backend/src:/code/app 
      - ./backend/data:/usr/local/miniconda3/lib/python3.11/site-packages
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=mvav-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - JWT_SECRET_KEY=hackme
    depends_on:
      db:
        condition: service_healthy

volumes:
  mvav_data:
    external: true
