version: "3.9"

services:
  db:
    container_name: mvav-db
    image: postgis/postgis
    ports:
      - 5432:5432
    volumes:
      - mvav_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mvav-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: psql -U postgres -c "select 1"
      interval: 2s
      retries: 10
      timeout: 1s
  backend:
    container_name: mvav-backend
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=mvav-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      db:
        condition: service_healthy

volumes:
  mvav_data:
    external: true
