from enum import Enum


class Regime(Enum):
    ZONE_30 = "ZONE 30"
    AIRE_PIETONNE = "AIRE PIETONNE"
    ZONE_DE_RENCONTRE = "ZONE DE RENCONTRE"
    EN_AGGLOMERATION = "EN AGGLOMERATION"
    HORS_AGGLOMERATION = "HORS AGGLOMERATION"
    AUTRE = "AUTRE"


class Amenagement(Enum):
    PISTE_CYCLABLE = "PISTE CYCLABLE"
    BANDE_CYCLABLE = "BANDE CYCLABLE"
    DOUBLE_SENS_CYCLABLE_PISTE = "DOUBLE SENS CYCLABLE PISTE"
    DOUBLE_SENS_CYCLABLE_BANDE = "DOUBLE SENS CYCLABLE BANDE"
    DOUBLE_SENS_CYCLABLE_NON_MATERIALISE = "DOUBLE SENS CYCLABLE NON MATERIALISE"
    VOIE_VERTE = "VOIE VERTE"
    VELO_RUE = "VELO RUE"
    COULOIR_BUS_VELO = "COULOIR BUS+VELO"
    RAMPE = "RAMPE"
    GOULOTTE = "GOULOTTE"
    AMENAGEMENT_MIXTE_PIETON_VELO_HORS_VOIE_VERTE = "AMENAGEMENT MIXTE PIETON VELO HORS VOIE VERTE"
    CHAUSSEE_A_VOIE_CENTRALE_BANALISEE = "CHAUSSEE A VOIE CENTRALE BANALISEE"
    ACCOTEMENT_REVETU_HORS_CVCB = "ACCOTEMENT REVETU HORS CVCB"
    AUCUN = "AUCUN"
    AUTRE = "AUTRE"


class Revetement(Enum):
    LISSE = "LISSE"
    RUGUEUX = "RUGUEUX"
    MEUBLE = "MEUBLE"


class Statut(Enum):
    EN_TRAVAUX = "EN TRAVAUX"
    EN_SERVICE = "EN SERVICE"
    PROVISOIRE = "PROVISOIRE"


class Emplacement(Enum):
    TROTTOIR = "TROTTOIR"
    INTERMEDIAIRE = "INTERMEDIAIRE"
    CHAUSSEE = "CHAUSSEE"


class Sens(Enum):
    UNIDIRECTIONNEL = "UNIDIRECTIONNEL"
    BIDIRECTIONNEL = "BIDIRECTIONNEL"


class Acces(Enum):
    ROLLER = "ROLLER"
    VELO_DE_ROUTE = "VELO DE ROUTE"
    VTC = "VTC"
    VTT = "VTT"
