version: "3.9"

services:
  db:
    environment:
      - POSTGRES_DB=mvav
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    container_name: backend
    build: ../backend
    ports:
      - 8000:8000
    environment:
      - POSTGRES_DB=mvav
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - JWT_SECRET_KEY=hackme
    depends_on:
      db:
        condition: service_healthy
