version: "3.9"

services:
  db:
    container_name: mvav-db
    image: postgis/postgis:15-3.4
    ports:
      - 5432:5432
    volumes:
      - mvav_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=mvav-dev
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: psql -U postgres -c "select 1"
      interval: 2s
      retries: 10
      timeout: 1s

volumes:
  mvav_data:
    external: true
